
# Option to view process metrics in MetricBrowser per PID OR as aggregated over all the processes with same name.
# If false, all the processes with same name are grouped and collective metrics are reported to AppDynamics Metric Browser.
# If true, each process with PID can be viewed but since PID changes with process restart, this might not be the best option.
displayByPid: false

# comma-separated names of processes you want to exclude out of the reported metrics.
#Example Linux  : java,bash,sshd
#Example Windows: java.exe,chrome.exe
excludeProcesses: [ ]

# comma-separated Process IDs (pids) to be excluded out of the reported metrics.
# Example: 2,343,1235,34
excludePIDs: [ ]

# Processes with an aggregated absolute memory consumption of LESS than this number
# in Megabytes will be filtered out of the reported metrics. Default value is 100 [MB]
memoryThreshold: 100

# ONLY for OS - WINDOWS
# csv.xsl file path - leave null for default location, 
# i.e. C:/Windows/SysWOW64/csv.xsl OR C:\\Windows\\SysWOW64\\webem\\en-US\\csv.xsl (for 64bit)
# OR C:/Windows/System32/csv.xsl (32 bit)
csvFilePath: ""

# this is the path to the file .monitored-processes
monitoredProcessFilePath: "monitors/ProcessMonitor/.monitored-processes"

metricPrefix: "Custom Metrics|"